# yarn install не запускает postinstall, если небыло изменения дерева зависимостей (https://github.com/yarnpkg/yarn/issues/5476).
# Фикс этого поведения через плагин https://github.com/mhassan1/yarn-plugin-after-install
afterInstall: yarn run postinstall

compressionLevel: mixed

# Не прятать вывод во время install
enableInlineBuilds: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
